package com.monetware.ringspider.base.dao;

import com.monetware.ringspider.base.model.BaseCompany;



public interface BaseCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int insert(BaseCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int insertSelective(BaseCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    BaseCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int updateByPrimaryKeySelective(BaseCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int updateByPrimaryKey(BaseCompany record);
}