package com.monetware.ringspider.base.dao;

import com.monetware.ringspider.base.model.BaseUser;

public interface BaseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int insert(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int insertSelective(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    BaseUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int updateByPrimaryKeySelective(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int updateByPrimaryKey(BaseUser record);
}