package com.monetware.ringspider.base.dao;

import com.monetware.ringspider.base.model.BaseMessage;

public interface BaseMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int insert(BaseMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int insertSelective(BaseMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    BaseMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int updateByPrimaryKeySelective(BaseMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_message
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int updateByPrimaryKey(BaseMessage record);
}