package com.monetware.ringspider.base.dao;

import com.monetware.ringspider.base.model.BaseSetting;

public interface BaseSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_setting
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_setting
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int insert(BaseSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_setting
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int insertSelective(BaseSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_setting
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    BaseSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_setting
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int updateByPrimaryKeySelective(BaseSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_setting
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    int updateByPrimaryKey(BaseSetting record);
}