package com.monetware.ringspider.base.dao;

import com.monetware.ringspider.base.model.BaseNews;

public interface BaseNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_news
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_news
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    int insert(BaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_news
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    int insertSelective(BaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_news
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    BaseNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_news
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    int updateByPrimaryKeySelective(BaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_news
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(BaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_news
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    int updateByPrimaryKey(BaseNews record);
}