package com.monetware.ringspider.base.model;

import java.util.Date;

public class BaseNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_news.id
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_news.news_name
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    private String newsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_news.news_pic
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    private String newsPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_news.create_time
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_news.order_by
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    private Integer orderBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_news.news_content
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    private String newsContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_news.id
     *
     * @return the value of web_news.id
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_news.id
     *
     * @param id the value for web_news.id
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_news.news_name
     *
     * @return the value of web_news.news_name
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public String getNewsName() {
        return newsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_news.news_name
     *
     * @param newsName the value for web_news.news_name
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public void setNewsName(String newsName) {
        this.newsName = newsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_news.news_pic
     *
     * @return the value of web_news.news_pic
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public String getNewsPic() {
        return newsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_news.news_pic
     *
     * @param newsPic the value for web_news.news_pic
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public void setNewsPic(String newsPic) {
        this.newsPic = newsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_news.create_time
     *
     * @return the value of web_news.create_time
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_news.create_time
     *
     * @param createTime the value for web_news.create_time
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_news.order_by
     *
     * @return the value of web_news.order_by
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public Integer getOrderBy() {
        return orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_news.order_by
     *
     * @param orderBy the value for web_news.order_by
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public void setOrderBy(Integer orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_news.news_content
     *
     * @return the value of web_news.news_content
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_news.news_content
     *
     * @param newsContent the value for web_news.news_content
     *
     * @mbg.generated Tue May 29 22:04:09 CST 2018
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent;
    }
}