package com.monetware.ringspider.base.model;

public class BaseMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_message.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_message.username
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_message.email
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_message.phone
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_message.content
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_message.id
     *
     * @return the value of web_message.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_message.id
     *
     * @param id the value for web_message.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_message.username
     *
     * @return the value of web_message.username
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_message.username
     *
     * @param username the value for web_message.username
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_message.email
     *
     * @return the value of web_message.email
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_message.email
     *
     * @param email the value for web_message.email
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_message.phone
     *
     * @return the value of web_message.phone
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_message.phone
     *
     * @param phone the value for web_message.phone
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_message.content
     *
     * @return the value of web_message.content
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_message.content
     *
     * @param content the value for web_message.content
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}