package com.monetware.ringspider.base.model;

public class BaseUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.username
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.password
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.nickname
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.email
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.phone
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.id
     *
     * @return the value of web_user.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.id
     *
     * @param id the value for web_user.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.username
     *
     * @return the value of web_user.username
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.username
     *
     * @param username the value for web_user.username
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.password
     *
     * @return the value of web_user.password
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.password
     *
     * @param password the value for web_user.password
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.nickname
     *
     * @return the value of web_user.nickname
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.nickname
     *
     * @param nickname the value for web_user.nickname
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.email
     *
     * @return the value of web_user.email
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.email
     *
     * @param email the value for web_user.email
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.phone
     *
     * @return the value of web_user.phone
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.phone
     *
     * @param phone the value for web_user.phone
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}