package com.monetware.ringspider.base.model;

public class BaseProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_product.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_product.product_name
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_product.product_intr
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String productIntr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_product.product_main_pic
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String productMainPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_product.product_cat
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private Integer productCat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_product.product_detail
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    private String productDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_product.id
     *
     * @return the value of web_product.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_product.id
     *
     * @param id the value for web_product.id
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_product.product_name
     *
     * @return the value of web_product.product_name
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_product.product_name
     *
     * @param productName the value for web_product.product_name
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_product.product_intr
     *
     * @return the value of web_product.product_intr
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getProductIntr() {
        return productIntr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_product.product_intr
     *
     * @param productIntr the value for web_product.product_intr
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setProductIntr(String productIntr) {
        this.productIntr = productIntr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_product.product_main_pic
     *
     * @return the value of web_product.product_main_pic
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getProductMainPic() {
        return productMainPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_product.product_main_pic
     *
     * @param productMainPic the value for web_product.product_main_pic
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setProductMainPic(String productMainPic) {
        this.productMainPic = productMainPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_product.product_cat
     *
     * @return the value of web_product.product_cat
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public Integer getProductCat() {
        return productCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_product.product_cat
     *
     * @param productCat the value for web_product.product_cat
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setProductCat(Integer productCat) {
        this.productCat = productCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_product.product_detail
     *
     * @return the value of web_product.product_detail
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public String getProductDetail() {
        return productDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_product.product_detail
     *
     * @param productDetail the value for web_product.product_detail
     *
     * @mbg.generated Wed Jun 27 11:20:46 CST 2018
     */
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail;
    }
}